### ISSUE TITLE
Fix Cleanup Logic

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-jenkinsscripts#20]
The cleanup logic does not allow the existing databases to remain intact. However, it should be possible to continue using the old data even after a new pull job. For this, the cleanup logic must be refactored so that it is possible that the existing database remains intact. This should be an optional option which depends on the existing flag "complete cleanup". 

Furthermore, the cleanup requires a Centos image at the moment. This image will be pulled from DockerHub. When DockerHub has some issues, we are unable to run our jobs. Therefore, The Centos image should be pulled from our own maintained artifactory.

**Comment by GoebelL** [comment]
> Furthermore, the cleanup requires a Centos image at the moment. This image will be pulled from DockerHub. When 
> DockerHub has some issues, we are unable to run our jobs. Therefore, The Centos image should be pulled from our own 
> maintained artifactory.

We do have centos in our private docker registry. The images are pulled from default registry (docker.io) only in case they are not present locally. In case, it happens DockerHub not to be available, you just pull those images from your own local registry before starting the job. Currently centos:7 and busybox:latest are required. This works well.
