### ISSUE TITLE
Docker Update

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-jenkinsscripts#28]
**Summary**
Test updated docker environment

**Acceptance criteria**
- [x] Jobs are successfull

**Additional context**
Ask me

**Comment by GoebelL** [comment]
Hi @kowalczyka 
Please add information which docker version at minimum is required for operating OSCM. We need to adapt the readme and manuals.

**Comment by kowalczyka** [comment]
Docker compose was updated to **1.27.4** and compose files were updated to version **3.8.** 
According to compatibility matrix (https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix) docker engine should be updated to **19.03.0+**
