### ISSUE TITLE
Runable build-base-and-push job 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-jenkinsscripts#42]
### Summary ### 
Provide a Jenkins pipeline configuration with ansible to run a [build-base-and-push](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/master/build-base-and-push.groovy) job.

### Details ###
* Find out requirements: 
   - Server: needed plug-ins or other resources, if any.
   - Agent: storage, memory, tools, users ..
 * Code playbook ([playbook](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/install/install/playbook/playbook.yml) details) 

### Acceptance criteria ### 
- [ ] Job is installable with playbook
- [ ] Job runs in OSCM Jenkins on local vagrant environment

**Comment by cworf91** [comment]
Part of this task is done within: 
https://github.com/servicecatalog/oscm-jenkinsscripts/pull/76
