### ISSUE TITLE
Runable pull-and-start job 

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-jenkinsscripts#46]
**Summary**

Provide a Jenkins pipeline configuration with ansible to run a build-base-and-push job.
**Details**

-    Find out requirements:
        Server: needed plug-ins or other resources, if any.
        Agent: storage, memory, tools, users ..

-   Code playbook ([playbook](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/install/install/playbook/playbook.yml) + details)

**Acceptance criteria**

[ ] Job is installable with playbook
[ ] Job runs in OSCM Jenkins on local vagrant environment
[ ] OSCM is deployed correctly and smoke tests are successful

**Comment by cworf91** [comment]
At the moment it is possible to install a master and a slave. The pipline pull-and-start pipline is also generated out of the box. However, there is still a problem with the permissions. The job must be executed as user "Jenkins". However, the user "Vagrant" is logged in at the time.

**Comment by GoebelL** [comment]
@cworf91 how is this state? Does the issue with the execution user still persist? 
In the end, we'll need a bit smoke testing in the UI to confirm if this jenkins job has done a good job (e.g. create new users, organizations and provision the sample service).
