### ISSUE TITLE
Fix proxy usage

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-jenkinsscripts#51]
**Version info**
v19.1 latest

**Describe the bug**
The proxy usage is more or less hardcoded in the groovy pipeline scripts.

**Details**
To run the Jenkins scripts without Proxy an import of the variables in the beginning of each script is necessary. 
Todo: 
- Create groovy script e.g. proxyvariables.groovy in the shared folder. The script could look like:
```if ${PROXY_HOST} exist; then
PROXY_OPTS=-Dhttp.proxyHost=${PROXY_HOST} -Dhttp.proxyPort=${PROXY_PORT}
else
PROXY_OPTS=""
fi
```
same for:
```
RUN_PROXY_ARGS=-e http_proxy="${http_proxy}" ...
BUILD_PROXY_ARGS=--build-arg http_proxy="${http_proxy}"
```

**Acceptance criteria**
- [ ] All code places matching "proxy" have been adapted
- [ ] Jobs are successfully running with proxy in respective network  
- [ ] Jobs can run successfully without proxy (in environment where it's not needed)

**Comment by GoebelL** [comment]
Hi @cworf91 
The proxy is still hardcoded in the WS tests, e.g. [here](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/cc7b0a871b4f5665a7f264252d77ca5ba93d0bdf/shared/test-webservices.groovy#L23). Further, I still get 4 matches when searching  "intern.est" in the grovy files. Please fix them.

**Comment by cworf91** [comment]
HI @GoebelL 
please check the state in the master branch [here](https://github.com/servicecatalog/oscm-jenkinsscripts/blob/master/shared/test-webservices.groovy). The proxy is configurable. I can´t reproduce the 4 matches for searching "intern.est". Do they also occure in the master branch?
