### ISSUE TITLE
Secure build secrets with  Azure Key Vault

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-jenkinsscripts#52]
**Details**
- Get familiar with Azure key vault and usage with ansible
e.g. https://www.youtube.com/results?search_query=use+azure+key+vault+with+ansible
- Setup a vault authentication using the service principal account of your application registered in Azure AD  
- Use existing test VM in Azure: Setup the client tools (ansible, Azure CLI, etc.)
- Consider playbooks and groovy scripts secrets to be stored in the vault
- Adapt parameter and defaults in Jenkins jobs

**Acceptance creteria**
- [x] Jenkins admin credentials are taken from vault
- [x] Ansible playbooks are and groovy scripts are secured

**Comment by GoebelL** [comment]
Let's rethink this. We better go with Azure Key Vault for our CI/CD pipeline. See also [my comment](https://github.com/servicecatalog/oscm-jenkinsscripts/issues/64#issuecomment-839878090) here.

**Comment by cworf91** [comment]
PR will be done in https://github.com/servicecatalog/oscm-jenkinsscripts/issues/73
