### ISSUE TITLE
Integrate vault into Playbook

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-jenkinsscripts#73]
**Summary**
Integrate vault into existing playbook

**Details**
The access to the vault and the gathering of the secrets is at the moment in extra playbook. This should be integratet into the existing

**Acceptance criteria**
[ ] Playbook is integratet and is working 

**Additional context**
Add any other context or screenshots about the task.

**Comment by GoebelL** [comment]
Done?
